version: '3.9'
services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        APP_ENV: ${APP_ENV}
        APP_PORT: ${APP_PORT}
    container_name: '${APP_NAME}-web'
    restart: on-failure
    volumes:
      - ./:/app
    ports:
      - '${APP_PORT}:${APP_PORT}'
    networks:
      - boilerplate-network
    extra_hosts:
      - host.docker.internal:host-gateway
networks:
  boilerplate-network:
    driver: bridge
